config/routes.rb
CopilotV0::Application.routes.draw do
  resources :travels do
      resources :stages do
        collection { post :sort }
       end
  end

   resources :januaries do
    collection { post :import }
  end

  resources :climates do
    collection { post :import }
  end

  root "climates#index"

  get "landing/landing3"
  get "landing/landing4"

  devise_for :users, controllers: { registrations: 'registrations'}
  get "home/index"
  get "home/profile"
  get "home/help"
  get "home/landing2"
  get "home/contact"
  get "home/about"
  get "landing/landing"
  get "landing/landing2"
  get "maps/index"
  get "travels/index"
  resources :prospects
  
  get "home/calculator"

end

app/models/travel.rb
require 'travel_calculator'

class Travel < ActiveRecord::Base

    belongs_to :user
    has_many :stages, -> { order(:stage_position) }

    def departure_travel
        self.initial_stage.departure_date
    end

    def add_stage(stage)
        self.stages << stage
    end

    def initial_stage
        self.stages.where(stage_position: 0).first
    end
    
    def stage_duration
        if self.initial_stage         #si Stage à stage_position 0 alors durée 0 et date de départ du Travel
             duration = 0
             departure_travel
        elsif self.stages.each {|s| s.duration.nil?}
            duration = self.stages.each {|s| s.departure_date - self.stages.find(stage_position: s.stage_position-1).departure_date}
        elsif self.stages.each {|s| s.departure_date.nil?}
            departure_date = self.stages.each {|s| self.stages.find(stage_position: s.stage_position-1).duration + self.stages.find(stage_position: s.stage_position-1).departure_date}
        end
    end

    def stages_quantity
        self.stages.count
    end
    
    def duration
        stages.sum(:duration)
    end

    def stage_date
        self.stages.each {|s| s.departure_date}
    end

    def chemin_optimal
        better = {}
        if self.stages.empty?
            return {}
        else
            available_stages = self.stages - [initial_stage]
            available_stages.each_with_index do |s, i|
                if s.geocoded?
                better[s.address] = s.distance_from(initial_stage).round 
                end
            end
        end
        better.sort_by{|s,i| i }
        # better_path(initial_stage, self.stages)
    end

    def meteo_path
        stages_with_notation = []
        self.stages.each do |s|
            if stages_with_notation.empty?
                s.notation = Climate.for_city_and_month(s.address.capitalize, s.departure_date.month).first.notation
                # (self.departure_date ++ s.duration).month)
                stages_with_notation.push s.notation
            elsif s.id.nil?
                next
            else
                s.notation = Climate.for_city_and_month(s.address.capitalize, s.departure_date.month).first.notation 
                stages_with_notation.push s.notation 
            end
       end
       p stages_with_notation
    end
    def climat
        stages_with_notation = []
        self.stages.each do |s|
            if stages_with_notation.empty?
                s.notation = Climate.for_city_and_month(s.address.capitalize, s.departure_date.month).first.notation
                stages_with_notation.push s.notation
            elsif s.id.nil?
                next
            else
                s.notation = Climate.for_city_and_month(s.address.capitalize, s.departure_date.month).first.notation 
                stages_with_notation.push s.notation 
            end
       end
       p stages_with_notation
    end

#       def climat
# +        stages_concerned = []
# +        self.stages.each do |s|
# +            if stages_concerned.empty?
# +                s = Climate.for_city_and_month(s.address.capitalize, s.departure_date.month)
# +                stages_concerned.push s
# +            elsif s.id.nil?
# +                next
# +            else
# +                s = Climate.for_city_and_month(s.address.capitalize, s.departure_date.month)
# +                stages_concerned.push s
# +                stages_concerned.flatten!
# +            end
# +       end
# +       p stages_concerned
# +    end

    # def self.global_notation
    #     if stages_with_notation.empty?
    #     return []

    # #A VERIFIER #à une date donnée, valeur attribuée à une t°
    #     def temperature_notation
    #         temperature_notations = []
    #         temperature_notation = 0
    #         self.stages.each do |s|
    #             if Climate.for_city_and_month(s.address.capitalize, s.departure_date.month).first.t_average > 40
    #                 temperature_notation = 1
    #             elsif Climate.for_city_and_month(s.address.capitalize, s.departure_date.month).first.t_average >= 35
    #                 temperature_notation = 2
    #             elsif Climate.for_city_and_month(s.address.capitalize, s.departure_date.month).first.t_average >= 28
    #                 temperature_notation = 3
    #             elsif Climate.for_city_and_month(s.address.capitalize, s.departure_date.month).first.t_average >= 23
    #                 temperature_notation = 4
    #             elsif Climate.for_city_and_month(s.address.capitalize, s.departure_date.month).first.t_average >= 21
    #                 temperature_notation = 5
    #             elsif Climate.for_city_and_month(s.address.capitalize, s.departure_date.month).first.t_average >= 17
    #                 temperature_notation = 4
    #             elsif Climate.for_city_and_month(s.address.capitalize, s.departure_date.month).first.t_average >= 13
    #                 temperature_notation = 3
    #             elsif Climate.for_city_and_month(s.address.capitalize, s.departure_date.month).first.t_average >= 8
    #                 temperature_notation = 2
    #             else Climate.for_city_and_month(s.address.capitalize, s.departure_date.month).first.t_average < 8
    #                 temperature_notation = 1
    #             end
    #         temperature_notations.sum << temperature_notation
    #         end
    #         temperature_notations
    #     end      

    # #A VERIFIER #à une date donnée, valeur attribuée à une hauteur de précipitation
    #     def precipitation_note
    #         precipitation_notations = []
    #         precipitation_notation = 0
    #         self.stages.each do |s|
    #             if Climate.for_city_and_month(s.address.capitalize, s.departure_date.month).first.precipitation.empty?
    #                 next
    #             else
    #                 if Climate.for_city_and_month(s.address.capitalize, s.departure_date.month).first.precipitation < 50
    #                     precipitation_notation = 5
    #                 elsif Climate.for_city_and_month(s.address.capitalize, s.departure_date.month).first.precipitation < 100
    #                     precipitation_notation = 4
    #                 elsif Climate.for_city_and_month(s.address.capitalize, s.departure_date.month).first.precipitation < 150
    #                     precipitation_notation = 3
    #                 elsif Climate.for_city_and_month(s.address.capitalize, s.departure_date.month).first.precipitation < 200
    #                     precipitation_notation = 2
    #                 else Climate.for_city_and_month(s.address.capitalize, s.departure_date.month).first.precipitation < 250
    #                     precipitation_notation = 1
    #                 end
    #             end
    #         precipitation_notations.sum << precipitation_notation
    #         end
    #         precipitation_notations
    #     end
    #     stages_with_notation = temperature_notation + precipitation
    # end



    def distance
        distance = 0
        bounds = stages.map{|s| [s.latitude, s.longitude]}
        for i in 0..(bounds.count - 1)
            unless i == (bounds.count - 1)
                distance += Geocoder::Calculations.distance_between(bounds[i], bounds[i+1])
            end
        end
        distance.round
    end

    def travel_budget
        budget = 0
        country_budget = 0
        self.stages.each do |stage|
            country_code = Geocoder.search(stage.address).first.country_code
            country_budget = Country.find_by(country_code: country_code).daily_budget * stage.duration
        budget += country_budget
    end
        budget
    end

    def azaz
        stages.order("stage_position").map{ |l| [l.latitude, l.longitude] }
    end


    # def country
    #     travel = Travel.find(params[:id])
    #     # city = travel.stages(stage_params).address
    #     # city = stages(stage_params[:address])
    #     @country = Geocoder.search(travel.stages(params[:address]).first.country

    #     @country
    # end

    # def info_ville
    #     GeoNamesAPI::Wikipedia.all(c.latitude, c.longitude)
    # end

    # def reverse_geocoded_by :latitude, :longitude do |obj,results|
    #         if geo = results.first
    #             obj.country = geo.country_code
    #         end
    #     end
    # after_validation :reverse_geocode
    # end

    # def add_stage(stage_params)
    #     puts "-" * 30
    #     puts stage_params
    #     stage_params = {stage_position: stages.count + 1}.merge(stage_params)
    #     puts stage_params
    #     puts "-" * 30
    #     stages.create(stage_params)
    # end


end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  before_action :set_travel, only: [:show, :edit, :update, :destroy]

  def index
    @travels = current_user.travels
    @gon = gon
  end

  def show
    @travel = Travel.find(params[:id])
    @stages = @travel.stages.order("stage_position")
    @stage =  @travel.stages.build
    # fill bounds: http://leafletjs.com/reference.html#latlngbounds
    @bounds = @stages.map{ |l| [l.latitude, l.longitude] }
    @chemin_optimal = @travel.chemin_optimal
    #@meteo_path = @travel.meteo_path
    #@climat = @travel.climat
  end

  def new
    @travel = current_user.travels.create(name: "TravelName")
    # @travel = current_or_guest_user.travels.create(name: "TravelName")
    #@guest = @travel.create_guest_user
    #session[:guest_user_id] = @guest.id
    @stage =  @travel.stages.build
  end

  def edit
  end

  def create
          redirect_to travel_path, notice: 'Travel was successfully created.'
  end

  def update
    respond_to do |format|
      if @travel.update(travel_params)
        format.html { redirect_to @travel, notice: 'Travel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @travel.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @travel.destroy
    respond_to do |format|
      format.html { redirect_to travels_url }
      format.json { head :no_content }
    end
  end

 
  private
    def set_travel
      @travel = Travel.find(params[:id])
    end

    def travel_params
      params.require(:travel).permit(:name, :nb_traveller)
    end

    def stage_params
       params.require(:stage).permit(:stage, :duration, :departure_date, :address)
    end
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/travels/_chart_script.html.erb
<script>
$(function () { 
	Highcharts.theme = {
    colors: ['#50B432', '#3498db', '#FFF263'],
    chart: {
        backgroundColor: {
            color: '#FFFFF',
            linearGradient: [0, 0, 0, 0],
            stops: [
                [0, 'rgb(255, 255, 255)']            
            ]
        }
    },
    title: {
        style: {
            color: '#000',
            font: 'bold 16px "Trebuchet MS", Verdana, sans-serif'
        }
    },
    subtitle: {
        style: {
            color: '#666666',
            font: 'bold 12px "Trebuchet MS", Verdana, sans-serif'
        }
    },

    legend: {
        itemStyle: {
            font: '9pt Trebuchet MS, Verdana, sans-serif',
            color: 'black'
        },
        itemHoverStyle:{
            color: 'black'
        }   
    }
};

// Apply the theme
Highcharts.setOptions(Highcharts.theme);

    $('#meteo').highcharts({
    	credits: {
            enabled: false
        },
        chart: {
            // type: 'line'
            renderTo: "travel",
        },
        tooltip: {
        	shared: true,
            backgroundColor: '#SCFFC5'
        },
				//     formatter: function() {
				//         return this.series.name + ':' + this.y + 'in' + this.x;
				//     },
				//     backgroundColor: '#SCFFC5',
				//     font_color: 'red',
				//     borderColor: 'black',
				//     borderRadius: 10,
				//     borderWidth: 3
				// },
				navigator: {
                adaptToUpdatedData: false,
                series : {
                    data : <%= @climat.map {|s| s.month} %>
                }
            },
        title: {
            text: 'Profil climatique prévisionnel'
        },
        legend: {
            borderRadius: 5,
            borderWidth: 1, 
            align: 'center',
     				verticalAlign: 'bottom',
        },
        xAxis: {
            type: 'Month',
            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        },

        yAxis: 
          [{ //--- Temperature yAxis
				    title: {
			        text: null,
				    },
				    labels: {
				    	format: '{value}°',
				    	style: {
                    fontSize: '10px'
                },
                x: -3
				    },  
					}, 
					{ //--- Rainfall yAxis
				    title: {
			        text: null,
				    },
				    labels: {
				    	format: '{value}mm',
				    	style: {
                    fontSize: '8px'
                },
                x: 3
				   
				    },
				  	opposite: true
					}],
        	series: [{
        		yAxis: 0,
        		type: 'spline',
				    name: 'Temperature',
				    data: <%= @climat.map {|s| s.t_average} %>,
				    lineWidth: 3,  
				    marker: {
                enabled: false,
                states: {
                    hover: {
                        enabled: true
                    }
                }
            },
            tooltip: {
                valueSuffix: '°C'
            },
            zIndex: 1,
            color: '#c0392b',
            negativeColor: '#48AFE8'
						},
						{
						yAxis: 1,
						type: 'column',
				    name: 'Rainfall',
						color: '#3498db',
            groupPadding: 0,
            pointPadding: 0,
            borderWidth: 0,
            shadow: false,
            dataLabels: {
                enabled: true,
                formatter: function () {
                    if (this.y > 0) {
                        return this.y;
                    }
                },
                style: {
                    fontSize: '8px'
                }
            },
            tooltip: {
                valueSuffix: 'mm'
            },
				    data: <%= @climat.map {|s| s.precipitation} %>
						},
						{
				    type: 'spline',
				    name: 'zone de confort',
				    color: '#16a085',
				    data: [23, 23, 23, 23, 23], 
				    dashStyle: 'ShortDashDot',
				    shadow: false,
				    pointPlacement: 'between',
				     marker: {
                enabled: false,
                states: {
                    hover: {
                        enabled: true
                    }
                }
              }
					}],
    });
});

</script>

app/views/travels/_form.html.erb
<%= minimal_form_for(@travel) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, :autofocus => true, placeholder: 'Travel title'%>
  </div>

  <div class="form-actions">
    <%= f.button :submit, label: 'Create a Travel' %>
  </div>
<% end %>

app/views/travels/_map_empty_script.html.erb
<script>

	var map = L.map('map').setView([51.505, -0.09], 3);

	L.tileLayer('http://{s}.tile.mapbox.com/v3/aj.Sketchy2/{z}/{x}/{y}.jpg', {
		attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>',
		subdomains: 'abcd',
		minZoom: 3,
		maxZoom: 16
	}).addTo(map);

	L.tileLayer('http://a{s}.acetate.geoiq.com/tiles/acetate-labels/{z}/{x}/{y}.png', {
		attribution: '&copy;2012 Esri & Stamen, Data from OSM and Natural Earth',
		subdomains: '0123',
		minZoom: 2,
		maxZoom: 18
	}).addTo(map);

</script>

app/views/travels/_map_script.html.erb
<script>

var osmLink = '<a href="http://openstreetmap.org">OpenStreetMap</a>',
            thunLink = '<a href="http://thunderforest.com/">Thunderforest</a>',
            watLink = '<a href="http://stamen.com">Stamen Design</a>',
            ccLink = '<a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>';

var osmUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    osmAttrib = '&copy; ' + osmLink + ' Contributors',
    landUrl = 'http://{s}.tile.thunderforest.com/landscape/{z}/{x}/{y}.png',
    thunAttrib = '&copy; '+osmLink+' Contributors & '+thunLink,
    watUrl = 'http://{s}.tile.stamen.com/watercolor/{z}/{x}/{y}.jpg',
    watAttrib = 'Map tiles by ' + watLink + ', ' + ccLink + '  &mdash; Map data &copy;' + osmLink + 'Contributors',
    acetUrl = 'http://a{s}.acetate.geoiq.com/tiles/acetate-labels/{z}/{x}/{y}.png',
    acetAttrib = '&copy; 2012 Esri & Stamen, Data from OSM and Natural Earth';

var osmMap = L.tileLayer(osmUrl, {attribution: osmAttrib}),
    landMap = L.tileLayer(landUrl, {attribution: thunAttrib}),
    watMap = L.tileLayer(watUrl, {attribution: watAttrib, minZoom: 0, maxZoom: 16}),
    acetMap = L.tileLayer(acetUrl, {attribution: acetAttrib, minZoom: 0, maxZoom: 18});

var watercolorMap = L.layerGroup([watMap, acetMap]);

var map = L.map('map',{layers: [watercolorMap]});

var bounds = <%= @bounds %> //=> [[lat0, lng0], [lat1, lng1]]
padded = L.latLngBounds( bounds ).pad(0.6)

map.fitBounds(padded)

var markers = []
for (index = 0; index < bounds.length; ++index) {
    marker = L.marker(bounds[index])
    marker.addTo(map)
    markers.push(marker)
};


var baseLayers = {
	"OSM Mapnik": osmMap,
	"Landscape": landMap,
	"watercolor": watercolorMap
};


var polyline = L.polyline(bounds, {color: 'black'}).addTo(map);



var control_layers = L.control.layers(baseLayers).addTo(map);



var input = document.getElementById('searchTextField');

var autocomplete = new google.maps.places.Autocomplete(input, options);
</script>

app/views/travels/_mini_map_script.html.erb
<script>


	var mini_map = L.map('<%= @gon.element %>',{zoom: 10, zoomControl:false, dragging:false, touchZoom:false, tap:false });

	var bounds = <%= @bounds %> //=> [[lat0, lng0], [lat1, lng1]]
	padded = L.latLngBounds( bounds ).pad(0.1)


	mini_map.fitBounds(padded)

	var markers = []
	for (index = 0; index < bounds.length; ++index) {
	    marker = L.marker(bounds[index])
	    marker.addTo(mini_map);
	    markers.push(marker);
	};

	L.tileLayer('http://{s}.tile.stamen.com/watercolor/{z}/{x}/{y}.jpg', {
		minZoom: 0,
		maxZoom: 16
	}).addTo(mini_map);

	L.tileLayer('http://a{s}.acetate.geoiq.com/tiles/acetate-labels/{z}/{x}/{y}.png', {
		minZoom: 0,
		maxZoom: 18
	}).addTo(mini_map);

	var polyline = L.polyline(bounds, {color: 'black'}).addTo(mini_map);


</script>

app/views/travels/edit.html.erb
<h1>Editing travel</h1>

<%= render 'form' %>

<%= link_to 'Show', @travel %> |
<%= link_to 'Back', travels_path %>

app/views/travels/index.html.erb
<div class="row">
  <h1>My travels</h1>
        <div class="button"><%= link_to 'New Travel', new_travel_path %></div>

  <div>
      <% @travels.each_with_index do |travel, i| %>
        <% @bounds = travel.azaz %>
        <% @gon.element = "mini_maps#{i}" %>
        <div>
          <%= travel.name %>
          <div class="mini_maps large-2 columns" id="<%= @gon.element %>" >
            <div><%= render 'mini_map_script' %></div>
          </div>

            <%= link_to 'Show', travel %>
            <%= link_to 'Delete', travel, method: :delete, data: { confirm: 'Are you sure?' } %>
            <ul class="inline-list">
              <li><%= travel.stages.count %><i class="fi-torsos picto" style="font-size: 24px;"></i></li> 
              <li><%= travel.stages.count %><i class="fi-marker" style="font-size: 24px;"></i></li>            
              <li><i class="fi-calendar" style="font-size: 24px;"></i><%= travel.duration %>d</li>
              <li><i class="fi-dollar-bill" style="font-size: 24px;"></i><%# @travel.travel_budget %>€</li>
              <li><i class="fi-share" style="font-size: 24px;"></i><%#  number_with_delimiter(@travel.distance, locale: :fr) %>km</li>
            </ul>
        </div>
      <% end %>
  </div>
</div>

app/views/travels/new.html.erb
<div id="map" style='position: absolute; left: 0px; top: 0px; overflow: hidden; width: 100%; height: 100%; z-index: -1;'>
</div>
 	<%= render 'map_empty_script' %>


<div>
	<%= render 'stages/new_stage_form' %>
</div>

app/views/travels/show.html.erb
<p id="notice"><%= notice %></p>

<div class="large-12 columns panel-landing-middle" style="z-index: 10">
  <div class="small-12 large-12 columns"><h1>Dresser la liste des étapes selon chemin optimal</h1></div>
    
  <div class="small-12 large-12 columns"><%= @travel.stages.first.address %><%= @chemin_optimal.flatten %></div>

  <div class="small-12 large-12 columns"><%# @meteo_path %></div>

  
</div>


<!-- 
- dresser la liste des étapes selon chemin optimal et reverse sur chmein optimal 
- afficher données météo de chaque étape pour chacun des chemins
- produire un graph mettant en forme ces données meteos. 1 graph/chemin puis tout sur un graph.
- indiquer le meilleur trajet climatique selon Copilot (sum notation)
- ajouter info bulle
- intégrer changement dynamique du graph dès que changement de position d'une étape.
-->


    <div id="map" style='position: absolute; left: 0px; top: 0px; overflow: hidden; width: 100%; height: 100%; z-index: 0;'></div>
  <%= render 'map_script' %>
 

<div class="small-3 large-3 small-offset-9 large-offset-9 columns panel" style="margin-top = -70px;">
  <div class="small-block-grid-12">
  <h1><%= @travel.name %><span class="handle"><%= link_to '[Edit]', edit_travel_path(@travel) %></span></h1>
  </div>

  <div class="row">
    <div class="small-2 columns">
        <label><i class="fi-torsos" style="font-size: 24px;"></i></label>
    </div>
    <div class="small-3 columns">
      <select id="right-label">
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
          <option value="6">6</option>
          <option value="7">7</option>
          <option value="8">8</option>
      </select>
    </div>
    <div class="small-2 columns">
      <%= @travel.stage_duration %>
        <label><i class="fi-loop" style="font-size: 24px;"></i><input type="checkbox" value="1"></label>
        <label><i class="fi-shuffle" style="font-size: 24px;"></i><input type="checkbox" value="1"></label>
    </div>
  </div>
  <table>
    <tr>
       
            <%= render 'stages/stages' %>
        
      
    </tr>
  </table>


<a href="#" data-reveal-id="myModal" class="button small radius">Add a stop</a>
<div id="myModal" class="reveal-modal" data-reveal>
  <%= render 'stages/new_stage_form' %>
  <a class="close-reveal-modal">&#215;</a>
</div>


<!--   <%# button_to "new stage", new_travel_stage_path(@travel, @stage), id: "add", method: :get, remote: true %>
 -->  <div class="row">
    <div class="small-4 columns">
      <%= @travel.stages.count-1 %>
      <i class="fi-marker" style="font-size: 24px;"></i>
    </div>
    
    <div class="small-4 columns">
      <i class="fi-calendar" style="font-size: 24px;"></i>
      <%= @travel.duration %>d
    </div>
    <div class="small-4 columns">
      <i class="fi-dollar-bill" style="font-size: 24px;"></i>
      <%# @travel.travel_budget %>€
    </div>
    <!-- <div class="small-3 columns end">
      <i class="fi-share" style="font-size: 24px;"></i>
      <%#  number_with_delimiter(@travel.distance, locale: :fr) %>km
    </div> -->
  </div>


  <div><%= button_to 'Save my trip', new_user_registration_path, method: :get %></div>
  <div id="meteo" style="width:100%; height:400px;z-index: 20"></div>
  <%# render 'chart_script' %>
  <div class="small-12 large-12 columns"><h1>Dresser la liste des étapes selon chemin optimal</h1></div>
</div>