config/routes.rb
CopilotV0::Application.routes.draw do
  resources :travels do
      resources :stages do
        collection { post :sort }
       end
  end

   resources :januaries do
    collection { post :import }
  end

  resources :climates do
    collection { post :import }
  end

  root "climates#index"

  get "landing/landing3"
  get "landing/landing4"

  devise_for :users, controllers: { registrations: 'registrations'}
  get "home/index"
  get "home/profile"
  get "home/help"
  get "home/landing2"
  get "home/contact"
  get "home/about"
  get "landing/landing"
  get "landing/landing2"
  get "maps/index"
  get "travels/index"
  resources :prospects
  
  get "home/calculator"

end

app/models/stage.rb
class Stage < ActiveRecord::Base
    attr_accessor :notation

    belongs_to :travel
    has_one :country, foreign_key: :country_code

    validates_presence_of :travel

    geocoded_by :address
    after_validation :geocode

# reverse_geocoded_by :latitude, :longitude
# after_validation :reverse_geocode  # auto-fetch address

	# def address
 #  		[city, country].compact.join(', ')
	# end

    def first_stage
        self.stage_position == 0
    end

    def end_date
        (travel.departure_date + self.duration ).to_s
    end

    def month_date
        (travel.departure_date + self.duration).month
    end

    def reverse_geocode_both
        start_coordinates = [self.from_lat, self.from_long]
        end_coordinates = [self.to_lat, self.to_long]
        self.from_string = Geocoder.address(start_coordinates)
        self.to_string = Geocoder.address(end_coordinates)
    end


    # def reverse_geocoded_by :latitude, :longitude do |obj,results|
    #         if geo = results.first
    #             obj.country = geo.country_code
    #         end
    #     end
    # after_validation :reverse_geocode
    # end

    def daily_budget
        country_code = Geocoder.search(self.address).first.country_code
        Country.find_by(country_code: country_code).daily_budget
    end

    def budget_by_address
        daily_budget * self.duration
    end
# code = Geocoder.search(pays).first.country_code
# info = Country.new(:country_code => "AU", :daily_budget => 60)
# money = Country.find_by(country_code: code).daily_budget

    def distance_from(other_stage)
      return 1 if other_stage == self || other_stage.nil?
      Geocoder::Calculations.distance_between(self.position, other_stage.position)
    end

    def position
      [self.latitude, self.longitude]
    end

end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
	def new
		@travel = Travel.find(params[:travel_id])
	  @stage = @travel.stages.build
		respond_to do |format|       
	    format.js
	  end
	end

	def create
		@travel = Travel.find(params[:travel_id])
		@stage = @travel.stages.new(stage_params)
		respond_to do |format|
		    if  @stage.save
		        format.html { redirect_to travel_path(@travel), notice: 'Stage was successfully created.' }
		        format.js
		    else
	       		format.html { render action: 'new' }
	      	end
	    end
	end
	
def destroy
    @stage = Stage.find(params[:id])
    if @stage.present?
      @stage.destroy
    end
    respond_to do |format|
	      format.html { redirect_to travel_route_stage_path }
	      format.js
	end
end

def sort
	sort_params[:stages_id].each_with_index do |stage, position|
		id = stage.split('_')[1]
        stage = Stage.find(id)
  	    stage.stage_position = position
  	    stage.save
  	end
	travel = Travel.find(params[:travel_id])
	render json: travel.stages.map{|s| [s.latitude, s.longitude]}
end





 private
    def sort_params
      params.permit(:stages_id => [])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stage_params
    	params.require(:stage).permit(:address, :departure_date, :duration, :travel_id, :stage_position)
    end

end

app/views/stages/_google.html.erb
<script>
// This example displays an address form, using the autocomplete feature
// of the Google Places API to help users fill in the information.

var placeSearch, autocomplete;
var componentForm = {
  street_number: 'short_name',
  route: 'long_name',
  locality: 'long_name',
  administrative_area_level_1: 'short_name',
  country: 'long_name',
  postal_code: 'short_name'
};

function initialize() {
  // Create the autocomplete object, restricting the search
  // to geographical location types.
  autocomplete = new google.maps.places.Autocomplete(
      /** @type {HTMLInputElement} */(document.getElementById('autocomplete')),
      { types: ['geocode'] });
  // When the user selects an address from the dropdown,
  // populate the address fields in the form.
  google.maps.event.addListener(autocomplete, 'place_changed', function() {
    fillInAddress();
  });
}

// Bias the autocomplete object to the user's geographical location,
// as supplied by the browser's 'navigator.geolocation' object.
function geolocate() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function(position) {
      var geolocation = new google.maps.LatLng(
          position.coords.latitude, position.coords.longitude);
      autocomplete.setBounds(new google.maps.LatLngBounds(geolocation,
          geolocation));
    });
  }
}
</script>

app/views/stages/_map_script.html.erb
<script>

	var map = L.map('map',{zoom: 200, minZoom: 2, maxZoom: 16});

var bounds = <%= @bounds %> //=> [[lat0, lng0], [lat1, lng1]]
padded = L.latLngBounds( bounds ).pad(0.6)

	map.fitBounds(padded)

	// marker = L.marker(bounds[0]).addTo(map)
	// marker = L.marker(bounds[1]).addTo(map);


	for (index = 0; index < bounds.length; ++index) {
	    marker = L.marker(bounds[index]).addTo(map);
	};

	// L.tileLayer('http://{s}.tiles.mapbox.com/v3/aj.Sketchy2//{z}/{x}/{y}.jpg')

	L.tileLayer('http://{s}.tile.stamen.com/watercolor/{z}/{x}/{y}.jpg', {
		attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>',
		subdomains: 'abcd',
		minZoom: 0,
		maxZoom: 16
	}).addTo(map);

	L.tileLayer('http://a{s}.acetate.geoiq.com/tiles/acetate-labels/{z}/{x}/{y}.png', {
		attribution: '&copy;2012 Esri & Stamen, Data from OSM and Natural Earth',
		subdomains: '0123',
		minZoom: 0,
		maxZoom: 18
	}).addTo(map);

	var polyline = L.polyline(bounds, {color: 'blue'}).addTo(map);

</script>


<!-- var Stamen_Watercolor = L.tileLayer('http://{s}.tile.stamen.com/watercolor/{z}/{x}/{y}.jpg', {
	attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>',
	subdomains: 'abcd',
	minZoom: 3,
	maxZoom: 16
});
var Acetate_labels = L.tileLayer('http://a{s}.acetate.geoiq.com/tiles/acetate-labels/{z}/{x}/{y}.png', {
	attribution: '&copy;2012 Esri & Stamen, Data from OSM and Natural Earth',
	subdomains: '0123',
	minZoom: 2,
	maxZoom: 18
}); -->

app/views/stages/_new_stage_form.html.erb
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
  <%= render 'stages/google' %>

<% if @stage == @travel.stages.first %>
	<div class="small-12 large-centered columns panel-bg" style="margin-top: 15%; padding: 5px; height: 50px; border-radius: 5px;">
	    <ul style="inline-block inline">
			<%= minimal_form_for @stage , url: travel_stages_path(@travel) do |s| %>
			<%= s.error_notification %>
				<div class="row">
					<ul class="inline-list">
						 <div class="small-7 large-7 columns"><%= s.input :address, placeholder: 'Where does your trip start ?', :autofocus => true %></div>

							<div class="small-3 large-3 columns"><%= s.text_field :departure_date, :id => "datepicker", placeholder: 'Departure date', label: 'Departure date' %></div>

						<div class="small-2 large-2 columns"><%= s.button :submit, value: 'Make a trip', class: "button small radius"%></div>
						<%= s.hidden_field :route_id %>
					</ul>
				</div>
			<% end %>
		</ul>
		<div class="small-centered large-centered small-3 large-3 small-offset-5 large-offset-5 columns panel" style="margin-top: 15%; padding: 5px; border-radius: 5px; text-align: center;">Already signed up ? <%= link_to("Log in", new_user_session_path) %> </div>
	</div>
<% else %>
	<%= minimal_form_for @stage , url: travel_stages_path(@travel) do |s| %>
	<%= s.error_notification %>
		<h2>Add a new Stop</h2>
		<div class="row">
			<body onload="initialize()">
    		<div id="locationField">
      			<input id="autocomplete" placeholder="Where do you want to go next ????" onFocus="geolocate()" type="text" value="<%# s.input %>"></input>
				</div>
				<div class="small-6 large-6 column" id="autocomplete"><%= s.input :address, placeholder: 'Where do you want to go next ?', :autofocus => true %></div>
				<div class="small-2 large-2 column"><%= s.date_field :departure_date, :id => "datepicker", placeholder: 'Departure date', label: 'Departure date' %>
 					 <%= s.telephone_field :duration, placeholder: 'Duration' %>
				</div>
				<div class="small-2 large-2 column"><%= s.button :submit, value: 'Next stop', class: "button small radius" %></div>
				<div class="small-2 large-2 column"><%= s.button :submit, value: 'Finish', class: "button small radius"%></div>
	  		</body>
		</div>
	<% end %>
<% end %>


<!-- , remote: true -->

app/views/stages/_stage.html.erb
<tr>
<td><span class="handle">[drag]</span><%= @stage.address %></td>
<td><%= @stage.duration %></td>
<td><%= @stage.departure_date %></td>
<td><%= button_to '-', travel_stages_path, remote: true, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/stages/_stages.html.erb
<tbody id="stage" data-update-url="<%= sort_travel_stages_url(@travel)%>">
<% stages_count = @stages.count %>
<% @stages.each do |stage| %>
<tr>
  <%= content_tag_for :td, stage do %>
    <% if stage.first_stage %>
    <div class="index">
      <span class="fi-flag"></span>
    </div>
    <% elsif stage.stage_position == stages_count-1 %>
    <div class="index">
      <span><i class="fa fa-flag-checkered"></i></span>
    </div>
    <% else %>
    <div class="index">
      <span><%= stage.stage_position %></span>
    </div>
    <% end %>
  <% end %>
  <td>
    <%= link_to h(stage.address), (@stage.travel) %>
  </td>
   <td> 
    <% if stage.first_stage %>
      <%= stage.duration = 0 %>
    <% else %>
      <%= stage.duration %>
    <% end %>
  </td>
  <td>
    <%= stage.departure_date %>
  </td>
  <!-- <td><%# @stages.find(stage.id+1).address %></td> -->
  <td><%= button_to '-', travel_stage_path(@travel, stage), remote: true, method: :delete, data: { confirm: 'Are you sure?' } %>
  </td>
  <% end %>
</tr>
</tbody>

app/views/stages/create.js.erb
$('#new_stage').remove();
$('#add').show();
$('#stage').append('<%= j render(@stage) %>');

app/views/stages/destroy.js.erb
$("#stage_<%= @stage.id %>").parent().fadeOut(500, function(){
	$(this).remove()
})
location.reload();

app/views/stages/new.js.erb
$('#add').hide().after('<%= j render ("new_stage_form") %>');