config/routes.rb
CopilotV0::Application.routes.draw do
  resources :travels do
      resources :stages do
        collection { post :sort }
       end
  end

   resources :januaries do
    collection { post :import }
  end

  resources :climates do
    collection { post :import }
  end

  root "climates#index"

  get "landing/landing3"
  get "landing/landing4"

  devise_for :users, controllers: { registrations: 'registrations'}
  get "home/index"
  get "home/profile"
  get "home/help"
  get "home/landing2"
  get "home/contact"
  get "home/about"
  get "landing/landing"
  get "landing/landing2"
  get "maps/index"
  get "travels/index"
  resources :prospects
  
  get "home/calculator"

end

app/models/prospect.rb
class Prospect < ActiveRecord::Base
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  before_action :set_prospect, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_user!

  # GET /prospects
  # GET /prospects.json
  def index
    @prospects = Prospect.all
  end

  # GET /prospects/1
  # GET /prospects/1.json
  def show
  end

  # GET /prospects/new
  def new
    @prospect = Prospect.new
  end

  # GET /prospects/1/edit
  def edit
  end

  # POST /prospects
  # POST /prospects.json
  def create
    @prospect = Prospect.new(prospect_params)

    respond_to do |format|
      if @prospect.save
        format.html { redirect_to :root, notice: 'Prospect was successfully created.' }
        format.json { render action: 'show', status: :created, location: @prospect }
      else
        format.html { render action: 'new' }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prospects/1
  # PATCH/PUT /prospects/1.json
  def update
    respond_to do |format|
      if @prospect.update(prospect_params)
        format.html { redirect_to @prospect, notice: 'Prospect was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prospects/1
  # DELETE /prospects/1.json
  def destroy
    @prospect.destroy
    respond_to do |format|
      format.html { redirect_to prospects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prospect
      @prospect = Prospect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prospect_params
      params.require(:prospect).permit(:email)
    end
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/views/prospects/_form.html.erb
<%= form_for(@prospect) do |f| %>
  <% if @prospect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prospect.errors.count, "error") %> prohibited this prospect from being saved:</h2>

      <ul>
      <% @prospect.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prospects/edit.html.erb
<h1>Editing prospect</h1>

<%= render 'form' %>

<%= link_to 'Show', @prospect %> |
<%= link_to 'Back', prospects_path %>

app/views/prospects/index.html.erb
<h1>Listing prospects</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @prospects.each do |prospect| %>
      <tr>
        <td><%= prospect.email %></td>
        <td><%= link_to 'Show', prospect %></td>
        <td><%= link_to 'Edit', edit_prospect_path(prospect) %></td>
        <td><%= link_to 'Destroy', prospect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prospect', new_prospect_path %>

app/views/prospects/new.html.erb
<h1>New prospect</h1>

<%= render 'form' %>

<%= link_to 'Back', prospects_path %>

app/views/prospects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @prospect.email %>
</p>

<%= link_to 'Edit', edit_prospect_path(@prospect) %> |
<%= link_to 'Back', prospects_path %>