config/routes.rb
CopilotV0::Application.routes.draw do
  resources :travels do
      resources :stages do
        collection { post :sort }
       end
  end

   resources :januaries do
    collection { post :import }
  end

  resources :climates do
    collection { post :import }
  end

  root "climates#index"

  get "landing/landing3"
  get "landing/landing4"

  devise_for :users, controllers: { registrations: 'registrations'}
  get "home/index"
  get "home/profile"
  get "home/help"
  get "home/landing2"
  get "home/contact"
  get "home/about"
  get "landing/landing"
  get "landing/landing2"
  get "maps/index"
  get "travels/index"
  resources :prospects
  
  get "home/calculator"

end

app/views/common/_footer.html.erb
<!-- <div class="panel panel-landing-footer footer">
		<ul class="small-block-grid-2 medium-block-grid-2 large-block-grid-2 no-bullet main">
			<li>
				<ul class="inline-list">
					<li>© 2014 Copilot.
					</li>
					<li>All Right Reserved
					</li>
					<li>Privacy Policy
					</li>
					<li>Terms of Use
					</li>
					<li>About
					</li>
					<li>Contact
					</li>
				</ul>
			</li>
			<li>
				<div style="text-align: center;">Brought to you by <a href="http://www.alkimya.co" target="_blank"><span id="alkimya">Alkimya</span><span id="alkimyaco">.co</span></a></div>
			</li>
		</ul>
</div> -->
<div class="panel panel-landing-footer footer">
	<ul class="inline-list">
		<ul class="small-block-grid-2 medium-block-grid-3 large-block-grid-6 no-bullet" style="margin-right:70px">
			<li> Privacy Policy</li>
			<li> Terms of Use</li>
			<li> About</li>
			<li> Contact</li>
			<li>© 2014 Copilot.All Right Reserved</li>
			<li>Brought to you by <a href="http://www.alkimya.co" target="_blank"><span id="alkimya">Alkimya</span><span id="alkimyaco">.co</span></a></li>
	</ul>
</div>

app/views/common/_side_bar.html.erb
<ul class="side-nav" id="lateral-bar">
	<dl>
		<li>
			<dd>
				<span data-tooltip data-options="disable_for_touch:true" class="tip-right" title="Travels">
					<%= link_to(travels_path) do %>
					<i class="fi-foundation"></i>
					<% end %>
				</span>
			</dd>
		</li>
		<li>
			<dd>
				<span data-tooltip data-options="disable_for_touch:true" class="tip-right" title="Budget">
					<%= link_to '<i class="fa fa-money"></i>'.html_safe, (home_help_path) %>
			</dd>
		</li>
		<li>
			<dd>
				<span data-tooltip data-options="disable_for_touch:true" class="tip-right" title="Check list">
					<%= link_to '<i class="fi-clipboard-pencil"></i>'.html_safe, (home_help_path) %>
				</span>

			</dd>
		</li>
		<li>
			<dd>
				<span data-tooltip data-options="disable_for_touch:true" class="tip-right" title="Climate">
					<%= link_to(home_help_path) do %>
					<i class="fa fa-umbrella"></i>
					<% end %>
				</span>
			</dd>
		</li>
		<li>
			<dd>
				<span data-tooltip data-options="disable_for_touch:true" class="tip-right" title="Roadmap">
					<%= link_to(home_help_path) do %>
					<i class="fa fa-road"></i>
					<% end %>
				</span>
			</dd>
		</li>
		<li>
			<dd><span data-tooltip data-options="disable_for_touch:true" class="tip-right" title="Explore other maps">
					<%= link_to '<i class="fa fa-lightbulb-o"></i>'.html_safe, (home_help_path) %>
				</span>

			</dd>
		</li>
		<li>
			<dd><span data-tooltip data-options="disable_for_touch:true" class="tip-right" title="Travel Shaker">
					<%= link_to '<i class="fa fa-magic"></i>'.html_safe, (home_help_path) %>
				</span>

			</dd>
		</li>
		</li>
			<li>
			<dd><span data-tooltip data-options="disable_for_touch:true" class="tip-right" title="Destinations">
					<%= link_to '<i class="fa fa-flag-checkered"></i>'.html_safe, (home_help_path) %>
				</span>

			</dd>
		</li>
		<li>
			<dd><span data-tooltip data-options="disable_for_touch:true" class="tip-right" title="Statistics about travel">
					<%= link_to '<i class="fi-graph-trend"></i>'.html_safe, (home_help_path) %>
				</span>

			</dd>
		</li>
		<li>
			<dd>
				<span data-tooltip data-options="disable_for_touch:true" class="tip-right" title="Lock">
					<%= link_to '<i class="fa fa-lock"></i>'.html_safe, (home_help_path) %>
				</span>

			</dd>
		</li>
		<li>
			<dd><span data-tooltip data-options="disable_for_touch:true" class="tip-right" title="FAQ">
					<%= link_to '<i class="fi-info"></i>'.html_safe, (home_help_path) %>
				</span>
			</dd>
		</li>
	</dl>
</ul>

app/views/common/_top_bar.html.erb
<div class="fixed">
  <nav class="top-bar" data-topbar data-options="is_hover: false">
    <ul class="title-area inline-list">
      <% if user_signed_in? %>
        <li><%= link_to(home_index_path) do %><%= image_tag('26945-NB.png', style:"height:3em; margin-top: 0.3em; ") %><% end %></li>
      <% else %>
        <li><%= link_to(root_path) do %><%= image_tag('26945-NB.png', style:"height:150px;") %><% end %></li>
      <% end %>
      <li><h1 class="main">COPILOT</h1></li>
    </ul>

<section class="top-bar-section">
  <!-- Right Nav Section -->
  <ul class="right hmenu">

    <% if user_signed_in? %>
      <li class="top_bar_user_name inline" >Hello <%= current_user.first_name %></li>
      <span style="margin-right: 10px;"></span>
      <li>
        <a href="#" data-dropdown="hover1" data-options="is_hover:true"><i class="fi-torso"></i></a>
        <ul id="hover1" class="f-dropdown" data-dropdown-content>
          <li class="down"><%= link_to 'Manage account ', home_profile_path %></li>
          <li class="down"><%= render "devise/shared/registration_items" %></li>
          <li class="down"><a href="#">Contact Support</a></li>
          <li class="down"><a href="#">Shop</a></li>
          <li class="active" style="text-align: center;"><%= render "devise/shared/login_items" %></li>
        </ul>
      </li>
      <li >
      <%= link_to(home_index_path) do %><i class="fi-mail"></i><% end %>
    </li>
    <% else %>
      <li>
        <%= render "devise/shared/login_items" %>
      </li>
      <li class="sign_up_button">
        <%= link_to('Sign up !', new_user_registration_path) %>
      </li>
    <% end %>
  </ul>
</section>
</nav>
</div>